### ISSUE TITLE
Templates e Provider - @Mutirao

### ISSUE THREAD

**Issue by uira** [redelivre/EditalDeRedes#1]
## Objetivo

Desenvolvimento de 4 temas em WordPress para Rede Livre e implementação e integração do provedor de identidade digital (Login Cidadão) com 4 plataformas digitais.

# Produtos

Detalhamento das tarefas a serem executadas

### Criação de quatro temas para WordPress. 
Os temas devem de código aberto e ser responsivos, modulares, customizáveis, com as seguintes características:

- [ ] #2  Um tema para **Pontos de Cultura**, integrado à plataforma Mapas Culturais (​https://github.com/hacklabr/mapasculturais​), que sincronize informações dos perfis de Agentes, Espaços, Eventos, Projeto e Oportunidades. **_// 45 dias_**

- [x] #3  Um tema para **Eventos e Festivais**, voltados para o segmento da música, desenvolvido com base na plataforma Toque No Brasil (​http://tnb.art.br​) e igualmente integrado ao Mapas Culturais. **_// 45 dias_**

- [x] #4   Um tema para **Lojas Online** integrado com pelo menos um dos seguintes sistemas de financiamento: Catarse, E-Dinheiro, Cielo, Pagseguro, Paypal, Pagar.me, Moip, VotoLegal, etc. **_// 45 dias_**

- [x] #5 Um Plugin voltado para comunicação instantânea, que faz a integração dos temas acima ao Webogram (​https://github.com/zhukov/webogram​), permitindo a interação entre o site wordpress e os grupos, canais, robôs e perfis do Telegram. **_// 45 dias_**

### Implementação e integração de **Provedor de Identidade Digital**

- [x] #6 Implementação e customização de Provedor de Identidade Digital Distribuída utilizando o software Login Cidadão. **_// 20 dias_**

- [x] #7 Integração do Provedor de Identidade Login Cidadão com o WordPress. **_// 20 dias_**

- [x] #8 Integração do Provedor de Identidade Login Cidadão com a plataforma Mapas Culturais. **_// 20 dias_**

- [ ] #9 Integração do Provedor de Identidade Login Cidadão com o Telegram. **_// 20 dias_**

- [ ] #10 Integração do Provedor de Identidade Login Cidadão com pelo menos um dos seguintes sistemas de financiamento: Catarse, E-dinheiro, Cielo, Pagseguro, Paypal e Moip. **_// 20 dias_**

## Cronograma de Entregas

- [x] [1)](milestone/1) Implementação e customização de Login Cidadão + integração do Login com WordPress + integração do Login Cidadão com o Mapa Cultural + Criação de tema do segmento da música

- [ ] [2)](milestone/2) Criação de tema para Pontos de Cultura + Integração do Login Cidadão com o Telegram + Integração do Login Cidadão com sistema de financiamento

- [ ] [3)](milestone/3) Criação de tema para Campanhas de Financiamento + Criação de tema para comunicação instantânea
